#ifndef _ASM_X86_UNISTD_32_H
#define _ASM_X86_UNISTD_32_H

/*
 * This file contains the system call numbers.
 */

#define __NR_restart_syscall      0
#define __NR_exit		  1
#define __NR_fork		  2
#define __NR_read		  3
#define __NR_write		  4
#define __NR_open		  5
#define __NR_close		  6
#define __NR_waitpid		  7
#define __NR_creat		  8
#define __NR_link		  9
#define __NR_unlink		 10
#define __NR_execve		 11
#define __NR_chdir		 12
#define __NR_time		 13
#define __NR_mknod		 14
#define __NR_chmod		 15
#define __NR_lchown		 16
#define __NR_break		 17
#define __NR_oldstat		 18
#define __NR_lseek		 19
#define __NR_getpid		 20
#define __NR_mount		 21
#define __NR_umount		 22
#define __NR_setuid		 23
#define __NR_getuid		 24
#define __NR_stime		 25
#define __NR_ptrace		 26
#define __NR_alarm		 27
#define __NR_oldfstat		 28
#define __NR_pause		 29
#define __NR_utime		 30
#define __NR_stty		 31
#define __NR_gtty		 32
#define __NR_access		 33
#define __NR_nice		 34
#define __NR_ftime		 35
#define __NR_sync		 36
#define __NR_kill		 37
#define __NR_rename		 38
#define __NR_mkdir		 39
#define __NR_rmdir		 40
#define __NR_dup		 41
#define __NR_pipe		 42
#define __NR_times		 43
#define __NR_prof		 44
#define __NR_brk		 45
#define __NR_setgid		 46
#define __NR_getgid		 47
#define __NR_signal		 48
#define __NR_geteuid		 49
#define __NR_getegid		 50
#define __NR_acct		 51
#define __NR_umount2		 52
#define __NR_lock		 53
#define __NR_ioctl		 54
#define __NR_fcntl		 55
#define __NR_mpx		 56
#define __NR_setpgid		 57
#define __NR_ulimit		 58
#define __NR_oldolduname	 59
#define __NR_umask		 60
#define __NR_chroot		 61
#define __NR_ustat		 62
#define __NR_dup2		 63
#define __NR_getppid		 64
#define __NR_getpgrp		 65
#define __NR_setsid		 66
#define __NR_sigaction		 67
#define __NR_sgetmask		 68
#define __NR_ssetmask		 69
#define __NR_setreuid		 70
#define __NR_setregid		 71
#define __NR_sigsuspend		 72
#define __NR_sigpending		 73
#define __NR_sethostname	 74
#define __NR_setrlimit		 75
#define __NR_getrlimit		 76   /* Back compatible 2Gig limited rlimit */
#define __NR_getrusage		 77
#define __NR_gettimeofday	 78
#define __NR_settimeofday	 79
#define __NR_getgroups		 80
#define __NR_setgroups		 81
#define __NR_select		 82
#define __NR_symlink		 83
#define __NR_oldlstat		 84
#define __NR_readlink		 85
#define __NR_uselib		 86
#define __NR_swapon		 87
#define __NR_reboot		 88
#define __NR_readdir		 89
#define __NR_mmap		 90
#define __NR_munmap		 91
#define __NR_truncate		 92
#define __NR_ftruncate		 93
#define __NR_fchmod		 94
#define __NR_fchown		 95
#define __NR_getpriority	 96
#define __NR_setpriority	 97
#define __NR_profil		 98
#define __NR_statfs		 99
#define __NR_fstatfs		100
#define __NR_ioperm		101
#define __NR_socketcall		102
#define __NR_syslog		103
#define __NR_setitimer		104
#define __NR_getitimer		105
#define __NR_stat		106
#define __NR_lstat		107
#define __NR_fstat		108
#define __NR_olduname		109
#define __NR_iopl		110
#define __NR_vhangup		111
#define __NR_idle		112
#define __NR_vm86old		113
#define __NR_wait4		114
#define __NR_swapoff		115
#define __NR_sysinfo		116
#define __NR_ipc		117
#define __NR_fsync		118
#define __NR_sigreturn		119
#define __NR_clone		120
#define __NR_setdomainname	121
#define __NR_uname		122
#define __NR_modify_ldt		123
#define __NR_adjtimex		124
#define __NR_mprotect		125
#define __NR_sigprocmask	126
#define __NR_create_module	127
#define __NR_init_module	128
#define __NR_delete_module	129
#define __NR_get_kernel_syms	130
#define __NR_quotactl		131
#define __NR_getpgid		132
#define __NR_fchdir		133
#define __NR_bdflush		134
#define __NR_sysfs		135
#define __NR_personality	136
#define __NR_afs_syscall	137 /* Syscall for Andrew File System */
#define __NR_setfsuid		138
#define __NR_setfsgid		139
#define __NR__llseek		140
#define __NR_getdents		141
#define __NR__newselect		142
#define __NR_flock		143
#define __NR_msync		144
#define __NR_readv		145
#define __NR_writev		146
#define __NR_getsid		147
#define __NR_fdatasync		148
#define __NR__sysctl		149
#define __NR_mlock		150
#define __NR_munlock		151
#define __NR_mlockall		152
#define __NR_munlockall		153
#define __NR_sched_setparam		154
#define __NR_sched_getparam		155
#define __NR_sched_setscheduler		156
#define __NR_sched_getscheduler		157
#define __NR_sched_yield		158
#define __NR_sched_get_priority_max	159
#define __NR_sched_get_priority_min	160
#define __NR_sched_rr_get_interval	161
#define __NR_nanosleep		162
#define __NR_mremap		163
#define __NR_setresuid		164
#define __NR_getresuid		165
#define __NR_vm86		166
#define __NR_query_module	167
#define __NR_poll		168
#define __NR_nfsservctl		169
#define __NR_setresgid		170
#define __NR_getresgid		171
#define __NR_prctl              172
#define __NR_rt_sigreturn	173
#define __NR_rt_sigaction	174
#define __NR_rt_sigprocmask	175
#define __NR_rt_sigpending	176
#define __NR_rt_sigtimedwait	177
#define __NR_rt_sigqueueinfo	178
#define __NR_rt_sigsuspend	179
#define __NR_pread64		180
#define __NR_pwrite64		181
#define __NR_chown		182
#define __NR_getcwd		183
#define __NR_capget		184
#define __NR_capset		185
#define __NR_sigaltstack	186
#define __NR_sendfile		187
#define __NR_getpmsg		188	/* some people actually want streams */
#define __NR_putpmsg		189	/* some people actually want streams */
#define __NR_vfork		190
#define __NR_ugetrlimit		191	/* SuS compliant getrlimit */
#define __NR_mmap2		192
#define __NR_truncate64		193
#define __NR_ftruncate64	194
#define __NR_stat64		195
#define __NR_lstat64		196
#define __NR_fstat64		197
#define __NR_lchown32		198
#define __NR_getuid32		199
#define __NR_getgid32		200
#define __NR_geteuid32		201
#define __NR_getegid32		202
#define __NR_setreuid32		203
#define __NR_setregid32		204
#define __NR_getgroups32	205
#define __NR_setgroups32	206
#define __NR_fchown32		207
#define __NR_setresuid32	208
#define __NR_getresuid32	209
#define __NR_setresgid32	210
#define __NR_getresgid32	211
#define __NR_chown32		212
#define __NR_setuid32		213
#define __NR_setgid32		214
#define __NR_setfsuid32		215
#define __NR_setfsgid32		216
#define __NR_pivot_root		217
#define __NR_mincore		218
#define __NR_madvise		219
#define __NR_madvise1		219	/* delete when C lib stub is removed */
#define __NR_getdents64		220
#define __NR_fcntl64		221
/* 223 is unused */
#define __NR_gettid		224
#define __NR_readahead		225
#define __NR_setxattr		226
#define __NR_lsetxattr		227
#define __NR_fsetxattr		228
#define __NR_getxattr		229
#define __NR_lgetxattr		230
#define __NR_fgetxattr		231
#define __NR_listxattr		232
#define __NR_llistxattr		233
#define __NR_flistxattr		234
#define __NR_removexattr	235
#define __NR_lremovexattr	236
#define __NR_fremovexattr	237
#define __NR_tkill		238
#define __NR_sendfile64		239
#define __NR_futex		240
#define __NR_sched_setaffinity	241
#define __NR_sched_getaffinity	242
#define __NR_set_thread_area	243
#define __NR_get_thread_area	244
#define __NR_io_setup		245
#define __NR_io_destroy		246
#define __NR_io_getevents	247
#define __NR_io_submit		248
#define __NR_io_cancel		249
#define __NR_fadvise64		250
/* 251 is available for reuse (was briefly sys_set_zone_reclaim) */
#define __NR_exit_group		252
#define __NR_lookup_dcookie	253
#define __NR_epoll_create	254
#define __NR_epoll_ctl		255
#define __NR_epoll_wait		256
#define __NR_remap_file_pages	257
#define __NR_set_tid_address	258
#define __NR_timer_create	259
#define __NR_timer_settime	(__NR_timer_create+1)
#define __NR_timer_gettime	(__NR_timer_create+2)
#define __NR_timer_getoverrun	(__NR_timer_create+3)
#define __NR_timer_delete	(__NR_timer_create+4)
#define __NR_clock_settime	(__NR_timer_create+5)
#define __NR_clock_gettime	(__NR_timer_create+6)
#define __NR_clock_getres	(__NR_timer_create+7)
#define __NR_clock_nanosleep	(__NR_timer_create+8)
#define __NR_statfs64		268
#define __NR_fstatfs64		269
#define __NR_tgkill		270
#define __NR_utimes		271
#define __NR_fadvise64_64	272
#define __NR_vserver		273
#define __NR_mbind		274
#define __NR_get_mempolicy	275
#define __NR_set_mempolicy	276
#define __NR_mq_open 		277
#define __NR_mq_unlink		(__NR_mq_open+1)
#define __NR_mq_timedsend	(__NR_mq_open+2)
#define __NR_mq_timedreceive	(__NR_mq_open+3)
#define __NR_mq_notify		(__NR_mq_open+4)
#define __NR_mq_getsetattr	(__NR_mq_open+5)
#define __NR_kexec_load		283
#define __NR_waitid		284
/* #define __NR_sys_setaltroot	285 */
#define __NR_add_key		286
#define __NR_request_key	287
#define __NR_keyctl		288
#define __NR_ioprio_set		289
#define __NR_ioprio_get		290
#define __NR_inotify_init	291
#define __NR_inotify_add_watch	292
#define __NR_inotify_rm_watch	293
#define __NR_migrate_pages	294
#define __NR_openat		295
#define __NR_mkdirat		296
#define __NR_mknodat		297
#define __NR_fchownat		298
#define __NR_futimesat		299
#define __NR_fstatat64		300
#define __NR_unlinkat		301
#define __NR_renameat		302
#define __NR_linkat		303
#define __NR_symlinkat		304
#define __NR_readlinkat		305
#define __NR_fchmodat		306
#define __NR_faccessat		307
#define __NR_pselect6		308
#define __NR_ppoll		309
#define __NR_unshare		310
#define __NR_set_robust_list	311
#define __NR_get_robust_list	312
#define __NR_splice		313
#define __NR_sync_file_range	314
#define __NR_tee		315
#define __NR_vmsplice		316
#define __NR_move_pages		317
#define __NR_getcpu		318
#define __NR_epoll_pwait	319
#define __NR_utimensat		320
#define __NR_signalfd		321
#define __NR_timerfd_create	322
#define __NR_eventfd		323
#define __NR_fallocate		324
#define __NR_timerfd_settime	325
#define __NR_timerfd_gettime	326
#define __NR_signalfd4		327
#define __NR_eventfd2		328
#define __NR_epoll_create1	329
#define __NR_dup3		330
#define __NR_pipe2		331
#define __NR_inotify_init1	332
#define __NR_preadv		333
#define __NR_pwritev		334
#define __NR_rt_tgsigqueueinfo	335
#define __NR_perf_event_open	336
#define __NR_recvmmsg		337

/* Numbers of modules call */
#define __SR_mod_exit		0
#define __SR_mod_printk		1
#define __SR_mod_mutex_lock	2
#define __SR_mod_kzalloc	3
#define __SR_mod_mutex_unlock	4
#define __SR_mod_kern_path	5
#define __SR_mod_call_usermodehelper 6
#define __SR_mod_kfree		7
#define __SR_mod_mutex_init	8
#define __SR_mod_securityfs_create_dir 9
#define __SR_mod_securityfs_create_file 10
#define __SR_modinput_allocate_device	11
#define __SR_modstrcpy	12
#define __SR_modacpi_device_hid	13
#define __SR_modacpi_enable_gpe	14
#define __SR_modsnprintf	15
#define __SR_modinput_unregister_device	16
#define __SR_modkfree	17
#define __SR_modseq_lseek	18
#define __SR_modproc_create_data	19
#define __SR_modblocking_notifier_chain_register	20
#define __SR_modinput_free_device	21
#define __SR_modblocking_notifier_call_chain	22
#define __SR_modinput_register_device	23
#define __SR_modacpi_root_dir	24
#define __SR_modkmem_cache_alloc	25
#define __SR_modacpi_bus_generate_proc_event	26
#define __SR_modprintk	27
#define __SR_modproc_mkdir	28
#define __SR_modinput_event	29
#define __SR_modstrcmp	30
#define __SR_modseq_read	31
#define __SR_modsprintf	32
#define __SR_modblocking_notifier_chain_unregister	33
#define __SR_modacpi_bus_unregister_driver	34
#define __SR_modremove_proc_entry	35
#define __SR_modseq_printf	36
#define __SR_mod__tracepoint_kmalloc	37
#define __SR_modsingle_release	38
#define __SR_modacpi_set_gpe_type	39
#define __SR_modacpi_evaluate_integer	40
#define __SR_modsingle_open	41
#define __SR_modkmalloc_caches	42
#define __SR_modacpi_bus_register_driver	43
#define __SR_modmktime	44
#define __SR_modalloc_chrdev_region	45
#define __SR_modidr_get_new	46
#define __SR_mod__class_create	47
#define __SR_mod_copy_from_user	48
#define __SR_moddev_set_name	49
#define __SR_moddevice_unregister	50
#define __SR_modkill_fasync	51
#define __SR_modclass_destroy	52
#define __SR_modflush_scheduled_work	53
#define __SR_modrtc_valid_tm	54
#define __SR_modadd_wait_queue	55
#define __SR_mod__wake_up	56
#define __SR_modget_device	57
#define __SR_mod__per_cpu_offset	58
#define __SR_moddev_driver_string	59
#define __SR_moddynamic_debug_enabled	60
#define __SR_modschedule	61
#define __SR_modput_device	62
#define __SR_mod__put_user_4	63
#define __SR_modrtc_tm_to_time	64
#define __SR_modpv_irq_ops	65
#define __SR_modcapable	66
#define __SR_modmodule_put	67
#define __SR_modidr_pre_get	68
#define __SR_modcdev_add	69
#define __SR_moddevice_create_file	70
#define __SR_modidr_remove	71
#define __SR_modadd_timer	72
#define __SR_mod_spin_unlock_irqrestore	73
#define __SR_modmutex_lock	74
#define __SR_modstrlcpy	75
#define __SR_modfasync_helper	76
#define __SR_modcopy_to_user	77
#define __SR_mod__tracepoint_module_get	78
#define __SR_mod_spin_lock_irq	79
#define __SR_mod__mutex_init	80
#define __SR_modmutex_lock_interruptible	81
#define __SR_moddevice_register	82
#define __SR_moddel_timer_sync	83
#define __SR_moddefault_wake_function	84
#define __SR_modper_cpu__cpu_number	85
#define __SR_mod__init_waitqueue_head	86
#define __SR_modjiffies	87
#define __SR_mod_spin_lock_irqsave	88
#define __SR_modunregister_chrdev_region	89
#define __SR_modmutex_unlock	90
#define __SR_modinit_timer_key	91
#define __SR_modschedule_work	92
#define __SR_modsimple_strtoul	93
#define __SR_moddynamic_debug_enabled2	94
#define __SR_modno_llseek	95
#define __SR_modremove_wait_queue	96
#define __SR_modrtc_time_to_tm	97
#define __SR_modrtc_month_days	98
#define __SR_modcdev_init	99
#define __SR_modper_cpu__current_task	100
#define __SR_modcdev_del	101
#define __SR_moddevice_remove_file	102
#define __SR_modclass_find_device	103
#define __SR_modhpet_rtc_timer_init	104
#define __SR_modfree_irq	105
#define __SR_moddev_get_drvdata	106
#define __SR_modplatform_driver_unregister	107
#define __SR_modplatform_get_irq	108
#define __SR_modsystem_state	109
#define __SR_modsysfs_create_bin_file	110
#define __SR_modacpi_clear_event	111
#define __SR_modis_hpet_enabled	112
#define __SR_modhpet_mask_rtc_irq_bit	113
#define __SR_mod__release_region	114
#define __SR_modhpet_rtc_interrupt	115
#define __SR_modbcd2bin	116
#define __SR_modrtc_lock	117
#define __SR_modpnp_get_resource	118
#define __SR_modhpet_register_irq_handler	119
#define __SR_modpnp_register_driver	120
#define __SR_modrequest_threaded_irq	121
#define __SR_modhpet_set_alarm_time	122
#define __SR_modplatform_get_resource	123
#define __SR_modacpi_disabled	124
#define __SR_modrtc_cmos_write	125
#define __SR_modrtc_cmos_read	126
#define __SR_modhpet_set_periodic_freq	127
#define __SR_modioport_resource	128
#define __SR_modrtc_update_irq	129
#define __SR_modbin2bcd	130
#define __SR_modacpi_gbl_FADT	131
#define __SR_modpnp_unregister_driver	132
#define __SR_modacpi_enable_event	133
#define __SR_modhpet_set_rtc_irq_bit	134
#define __SR_mod__const_udelay	135
#define __SR_modacpi_disable_event	136
#define __SR_mod_spin_lock	137
#define __SR_modrtc_device_unregister	138
#define __SR_moddev_set_drvdata	139
#define __SR_modacpi_install_fixed_event_handler	140
#define __SR_modhpet_unregister_irq_handler	141
#define __SR_modset_irq_wake	142
#define __SR_modsysfs_remove_bin_file	143
#define __SR_modrtc_device_register	144
#define __SR_mod__request_region	145
#define __SR_modplatform_driver_probe	146
#define __SR_modadd_uevent_var	147
#define __SR_modpci_save_state	148
#define __SR_modyield	149
#define __SR_mod_unlock_kernel	150
#define __SR_moddma_ops	151
#define __SR_modd_instantiate	152
#define __SR_moddma_pool_create	153
#define __SR_modbus_unregister_notifier	154
#define __SR_modwait_for_completion_timeout	155
#define __SR_modsimple_dir_inode_operations	156
#define __SR_modpci_enable_device	157
#define __SR_modlookup_one_len	158
#define __SR_modnew_inode	159
#define __SR_modcomplete	160
#define __SR_modsecurity_task_getsecid	161
#define __SR_moddriver_remove_file	162
#define __SR_modinit_special_inode	163
#define __SR_modunregister_filesystem	164
#define __SR_modsysfs_add_file_to_group	165
#define __SR_modparam_get_bool	166
#define __SR_moddriver_attach	167
#define __SR_modfinish_wait	168
#define __SR_modpci_back_from_sleep	169
#define __SR_modsimple_statfs	170
#define __SR_modup	171
#define __SR_modpci_prepare_to_sleep	172
#define __SR_modiounmap	173
#define __SR_moddevice_initialize	174
#define __SR_modkref_get	175
#define __SR_mod__printk_ratelimit	176
#define __SR_modprepare_to_wait	177
#define __SR_modmemcpy	178
#define __SR_modkthread_create	179
#define __SR_modkref_init	180
#define __SR_modiput	181
#define __SR_modget_driver	182
#define __SR_modkthread_should_stop	183
#define __SR_modfree_pages	184
#define __SR_modregister_filesystem	185
#define __SR_mod__phys_addr	186
#define __SR_moddevice_create_bin_file	187
#define __SR_mod__suspend_report_result	188
#define __SR_modwake_up_process	189
#define __SR_moddma_pool_alloc	190
#define __SR_modrefrigerator	191
#define __SR_modschedule_timeout	192
#define __SR_modmsecs_to_jiffies	193
#define __SR_modschedule_delayed_work	194
#define __SR_mod__get_free_pages	195
#define __SR_modsimple_dir_operations	196
#define __SR_moddriver_create_file	197
#define __SR_modioremap_nocache	198
#define __SR_modbus_register_notifier	199
#define __SR_modstrrchr	200
#define __SR_modsynchronize_irq	201
#define __SR_moddma_alloc_from_coherent	202
#define __SR_modcontig_page_data	203
#define __SR_modkill_pid_info_as_uid	204
#define __SR_modbus_unregister	205
#define __SR_moddown_write	206
#define __SR_modup_write	207
#define __SR_mod__create_workqueue_key	208
#define __SR_modbus_find_device	209
#define __SR_moddevice_add	210
#define __SR_modmatch_int	211
#define __SR_moddma_release_from_coherent	212
#define __SR_moddma_pool_free	213
#define __SR_modinit_uts_ns	214
#define __SR_modmod_timer	215
#define __SR_moddevice_create	216
#define __SR_modput_driver	217
#define __SR_moddown	218
#define __SR_moddevice_attach	219
#define __SR_moddentry_unhash	220
#define __SR_moddestroy_workqueue	221
#define __SR_moddcache_lock	222
#define __SR_modwarn_slowpath_null	223
#define __SR_moddebugfs_remove	224
#define __SR_modstrncpy	225
#define __SR_modparam_set_bool	226
#define __SR_moddriver_unregister	227
#define __SR_modfind_next_zero_bit	228
#define __SR_modd_alloc_root	229
#define __SR_modpci_power_names	230
#define __SR_modsysfs_remove_file_from_group	231
#define __SR_modsysfs_create_group	232
#define __SR_modkthread_stop	233
#define __SR_modsscanf	234
#define __SR_moddown_trylock	235
#define __SR_modmovable_zone	236
#define __SR_mod_ctype	237
#define __SR_moddevice_del	238
#define __SR_modkill_litter_super	239
#define __SR_moddevice_bind_driver	240
#define __SR_modmemset	241
#define __SR_modget_sb_single	242
#define __SR_modpci_set_master	243
#define __SR_modwait_for_completion	244
#define __SR_modd_delete	245
#define __SR_modkasprintf	246
#define __SR_moddown_read	247
#define __SR_modkstrdup	248
#define __SR_modsysfs_remove_group	249
#define __SR_mod_lock_kernel	250
#define __SR_moddma_pool_destroy	251
#define __SR_moddebugfs_create_file	252
#define __SR_modparam_set_int	253
#define __SR_modstrsep	254
#define __SR_modcancel_delayed_work_sync	255
#define __SR_modx86_dma_fallback_dev	256
#define __SR_modsg_next	257
#define __SR_mod__register_chrdev	258
#define __SR_modqueue_work	259
#define __SR_modmatch_token	260
#define __SR_mod__get_user_4	261
#define __SR_moddevice_destroy	262
#define __SR_modcancel_work_sync	263
#define __SR_moddput	264
#define __SR_modgeneric_delete_inode	265
#define __SR_modutf16s_to_utf8s	266
#define __SR_modpci_disable_device	267
#define __SR_modcurrent_kernel_time	268
#define __SR_modsimple_release_fs	269
#define __SR_modautoremove_wake_function	270
#define __SR_modmatch_octal	271
#define __SR_modregister_chrdev_region	272
#define __SR_modpage_address	273
#define __SR_moddevice_release_driver	274
#define __SR_modstrlen	275
#define __SR_modiomem_resource	276
#define __SR_moddel_timer	277
#define __SR_modparam_get_int	278
#define __SR_modmem_map	279
#define __SR_moddebugfs_create_dir	280
#define __SR_modup_read	281
#define __SR_moddriver_register	282
#define __SR_modput_pid	283
#define __SR_modkref_put	284
#define __SR_modmsleep	285
#define __SR_mod__kmalloc	286
#define __SR_moddevice_remove_bin_file	287
#define __SR_modsimple_pin_fs	288
#define __SR_modbus_register	289
#define __SR_mod__unregister_chrdev	290

#ifdef __KERNEL__

#define NR_syscalls 		338
#define SR_modcalls		291

#define __ARCH_WANT_IPC_PARSE_VERSION
#define __ARCH_WANT_OLD_READDIR
#define __ARCH_WANT_OLD_STAT
#define __ARCH_WANT_STAT64
#define __ARCH_WANT_SYS_ALARM
#define __ARCH_WANT_SYS_GETHOSTNAME
#define __ARCH_WANT_SYS_PAUSE
#define __ARCH_WANT_SYS_SGETMASK
#define __ARCH_WANT_SYS_SIGNAL
#define __ARCH_WANT_SYS_TIME
#define __ARCH_WANT_SYS_UTIME
#define __ARCH_WANT_SYS_WAITPID
#define __ARCH_WANT_SYS_SOCKETCALL
#define __ARCH_WANT_SYS_FADVISE64
#define __ARCH_WANT_SYS_GETPGRP
#define __ARCH_WANT_SYS_LLSEEK
#define __ARCH_WANT_SYS_NICE
#define __ARCH_WANT_SYS_OLD_GETRLIMIT
#define __ARCH_WANT_SYS_OLDUMOUNT
#define __ARCH_WANT_SYS_SIGPENDING
#define __ARCH_WANT_SYS_SIGPROCMASK
#define __ARCH_WANT_SYS_RT_SIGACTION
#define __ARCH_WANT_SYS_RT_SIGSUSPEND

/*
 * "Conditional" syscalls
 *
 * What we want is __attribute__((weak,alias("sys_ni_syscall"))),
 * but it doesn't work on all toolchains, so we just do it by hand
 */
#ifndef cond_syscall
#define cond_syscall(x) asm(".weak\t" #x "\n\t.set\t" #x ",sys_ni_syscall")
#endif

#endif /* __KERNEL__ */
#endif /* _ASM_X86_UNISTD_32_H */
